### ISSUE TITLE
Remove the unused files from the project

### ISSUE THREAD

**Issue by jogendra** [jogendra/HealthLedger#10]
**Actual Behaviour**

Many unused HTML/CSS/JS files or CDN links are presents in the project.

**Expected Behaviour**

Remove the unused files/links from the project

**Would you like to work on the issue?**

Anyone can claim the issue :) Feel free to comment.

**Comment by LalitSharma7** [comment]
@jogendra can i work on this too??

**Comment by jogendra** [comment]
Sure @Rattlecode17sh
