### ISSUE TITLE
Improve SEO tags on the web page

### ISSUE THREAD

**Issue by jogendra** [jogendra/HealthLedger#11]
**Expected Behaviour**
The SEO tags are presents on some pages and some missing some tags, please add tags as well as website icons(.ico).

**Would you like to work on the issue?**

Anyone can take this issue. Drop a comment if you want to claim.

**Comment by devgupta2607** [comment]
How to work with SEO ?

**Comment by thesmallstar** [comment]
I will work on this :)

**Comment by jogendra** [comment]
Sure @thesmallstar go ahead :)

**Comment by thesmallstar** [comment]
@jogendra  the only meta tags I Can add with current information is title and description. I find other meta tags to be irrelevant at this point. What do you suggest?

**Comment by jogendra** [comment]
@thesmallstar Okay that is fine. The meta tags should be presented on all the pages along with favicon.

**Comment by thesmallstar** [comment]
@jogendra  okay :)

**Comment by jogendra** [comment]
Fixed in https://github.com/jogendra/HealthLedger/pull/15
