### ISSUE TITLE
Improve navbar on pages except homepage

### ISSUE THREAD

**Issue by jogendra** [jogendra/HealthLedger#14]
**Actual Behaviour**

Navbar on the pages os not well designed

**Expected Behaviour**

Improve the UI/UX of navbar on all the pages except homepage

**Would you like to work on the issue?**

Anyone can claim this issue. feel free to drop a comment.

**Comment by anupm12** [comment]
I want to work on this

**Comment by jogendra** [comment]
Sure @anupm12 Go ahead :)

**Comment by jogendra** [comment]
Hey @anupm12 are you still working on this?

**Comment by anupm12** [comment]
Yes @jogendra 
Currently I'm working on this.
Will be done today.

**Comment by jogendra** [comment]
@anupm12 cool!

**Comment by anupm12** [comment]
Please review my pr @jogendra
