### ISSUE TITLE
Add Gitter badge and communication section to README

### ISSUE THREAD

**Issue by jogendra** [jogendra/HealthLedger#16]
**Expected Behaviour**

- Add Gitter badge to the readme
Use this bedge **[![Gitter](https://badges.gitter.im/jogendra/HealthLedger.svg)](https://gitter.im/jogendra/HealthLedger?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)**
- Add **Communication** section to readme (Refer [this](https://github.com/fossasia/susi_iOS#communicationhttps://github.com/fossasia/susi_iOS#communication))

**Would you like to work on the issue?**

Anyone can claim the issue

**Comment by sourabhpruthi10** [comment]
@jogendra i will work on this

**Comment by jogendra** [comment]
Sure @sourabh1031
