### ISSUE TITLE
Disable scrolling on home page

### ISSUE THREAD

**Issue by jogendra** [jogendra/HealthLedger#3]
**Actual Behaviour**

The homepage is little scrollable

**Expected Behaviour**

It should cover screen only, and should not be scrollable.

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Anyone can claim the issue

**Comment by AhmedElbohoty** [comment]
Hello. 
I made a pull request to fix this issue #3.

I don't use bootstrab or now-ui-kit . 

But, If you want to handle your website with React and vanilla CSS, I can do it.

I can make branch and start working on react if you want that . 

Nice to meet you. 

:)

**Comment by jogendra** [comment]
Issue transferred to https://github.com/NJACKWinterOfCode/HealthLedger/issues/1

**Comment by jogendra** [comment]
Hi @AhmedElbohoty Sorry for replying late, I was busy with my end semester exams. Please submit your PR to https://github.com/NJACKWinterOfCode/HealthLedger. Your contributions will be count for PRs made after December 1. Also, you can use React and Vanilla CSS. Thanks
